import React from 'react';
import LocalizedStrings from 'react-native-localization';
const strings = new LocalizedStrings({
"en":{
    singIn:"SIGN IN",
    singUp:"SIGN UP",
    emailID:"Email Id",
    enterEmailID:"Enter Email Id",
    password:"Password",
    enterPassword:"Enter Password",
    forgotPassword:"Forgot Password",
    forgotPasswordCaps:"FORGOT PASSWORD",
    privacyPolicy:"Privacy Policy",
    aboutUs:"About Us",
    signWithFacebook:"SIGN WITH FACEBOOK",
    city:"City",
    enterCity:"Enter City",
    name:"Name",
    enterName:"Enter Name",
    phoneNo:"Phone Number",
    enterPhoneNo:"Enter Phone Number",
    permissionDenied:"Permission Denied",
    emailCanNotBlank:"Email can not be blank",
    enterValidEmail:"Enter the Valid mail id",
    passwordCanNotBlank:"Password can not be blank",
    passwordMust6Long:"Password must be 6 charater long",
    pleaseEnterEmailID:"Please enter email ID",
    acceptPrivacyPolicy:"Please accept Privacy Policy",
    cityCantBlank:"City can not be blank",
    nameCantBlank:"Name can not be blank",
    numberCantBlank:"Number can not be blank",
    enterValidPhoneNo:"Enter the Valid Phone No",
    typeHere:"Type here",
    notification:"Notification",
    category:"Category",
    items:"Items",
    filter:"Filter",
    reset:"Reset",
    done:"Done",
    sortBy:"Sort by",
    costLTH:"Cost(Low \nto High)",
    costHTL:"Cost(High \nto Low)",
    mostPopular:"Most \n Popular",
    nearestMe:"Nearest Me",
    shop:"Shops",
    search:"Search",
    price:"Price",
    min:"Min",
    max:"Max",
    chat:"Chat",
    cart:"Cart",
    subTotal:"Subtotal",
    deliveryChanges:"Delivery charges",
    tax:"Tax",
    totalAmount:"Total Amount",
    checkOut:"Checkout",
    profile:"Profile",
    address:"Address",
    orderHistory:"Order History",
    currentOrder:"Current Order",
    wishList:"Wishlist",
    payment:"Payment",
    setting:"Setting",
    shareApp:"Share App",
    logOut:"LogOut",
    gps:"GPS",
    sms:"SMS",
    email:"Email",
    deleteAccount:"Delete Account",
    clearHistory:"Clear History",
    paymentPurchaseTerm:"Make your payment now and benefit from 3% reduction on the total of your purchases",
    airtelMoney:"Airtel Money",
    mtnMobileMoney:"MTN Mobile Money(Available soon)",
    paymentOnDelivery:"Make your payment on delivery",
    cod:"Cash on delivery",
    outOfstock:"Out of stock",
    orderId:"Order Id",
    purchaseDateTime:"Purchase Date & Time",
    estDelivery:"Est.Delivery",
    orderAmount:"Order Amount",
    currentStatus:"Current Status",
    trackYourOrder:"Track Your Order",
    orderPlaced:"Order Placed",
    orderConfirm:"Order Confirm",
    packed:"Packed",
    shiped:"Shipped",
    delivered:"Delivered",
    price:"Price",
    item:"Item",
    userCurrentLocation:"Use Current Location",
    addNewAddress:"Add a new address",
    referencePoint:"Reference Point",
    enterReferencePoint:"Enter Reference Point",
    street1:"Street1",
    enterStreet:"Enter Street",
    neighbourhood:"Neighbourhood",
    selectNeighbourhood:"Select neighbourhood",
    state:"state",
    enterState:"Enter State",
    phoneNo:"Phone No",
    enterPhoneNo:"Enter Phone No",
    pincode:"Pincode",
    enterPinCode:"Enter Pincode No",
    pleaseEnterAllFields:"Please enter all fields",
    pleaseSelectNeighBourhood:"Please Select Neightbourhood",
    successfullyUpdate:"Successfully update",
    changeLanguage:"Change Language",
    delete:"Delete",
    edit:"Edit",
    successfullyAdded:"Successfully Added",
    cartEmpty:"Your cart is currently empty.",
    dateNTime:"Date & Time",
    noDataFound:"No Data found",
    cancelOrder:"Cancel Order",
    confirmYourPayment:"Confirm your payment",
    orText:"Or",
    updateProfile:"Update Profile",
    updateText:"Update",
    changePassword:"Change Password",
    currentPassword:"Current password",
    newPassword:"New password",
    reEnterPassword:"Re-enter password",
    passwordDoesntMatch:"Password doesn\'t match",
    afamapmh6c:"All fields are mandatory and password must have at least 6 characters",
    paymentDoneSuccessfullyOrder:"Payment Done Successfully and Your Order",
    isConfirmed:"Is Confirmed",
    thanksForOrder:"Thanks for placing order with NYOTA",
    registerPassword:"Password",
    rating:"Rating",
    okText:"OK",
    rateItText:"Rate it !",
    selectAddressFirst:"Please select Address First",
    makePaymentOf:"Make Payment of",
    noMoreItemAvailable:"No More Items available",
    reachWithmaxPrice:"You are reached with maximum price to buy product",
    selectSortOption:"Please select sort option",
    giveRatingToProduct:"Please give rating to the product",
    aboutThisProduct:"About this product",
    commentText:"Comments",
    viewAllText:"View all",
    similarProductText:"Similar Products",
    rateTheProduct:"Rate the Product",
    goodText:"Good",
    excellentText:"Excellent",
    horribleText:"Horrible",
    badText:"Bad",
    moreReviewText:"More detailed reviews get more visibility...",
    engText:"English",
    frenchText:"French",
    deliveryOption:'Delivery Options',
    standard:'Standard',
    express:'Express',
    updateOrder:'Update Order',
    updateOrderHeader:'Update Order',
    addingProductPopOption:'Adding product in exisiting order',
    addingExistingPopOption:'Adding product and merge with your current cart if card not exist will create',
    addnewProduct:'Add new Product',
    addMoreProduct:'Add More Product',
    cancel:'Cancel',
    submit:'Submit',
    popupNote:'*exisiting cart will be merge with your existing order',
    modification:'Modification',
    shippingPrice:'Shipping Price'
  },
"fr":{
    singIn:"Se connecter",
    singUp:"Créer un compte",
    emailID:"E-mail",
    enterEmailID:"Indiquez votre e-mail",
    password:"Votre mot de passe",
    enterPassword:"Saisissez votre mot de passe",
    forgotPassword:"Mot de passe oublié?",
    forgotPasswordCaps:"Mot de passe oublié?",
    privacyPolicy:"Notre politique de confidentialité",
    aboutUs:"À propos de NYOTA",
    signWithFacebook:"S'INSCRIRE AVEC FACEBOOK",
    city:"Ville",
    enterCity:"Indiquez votre ville",
    name:"Nom",
    enterName:"Renseignez votre Nom",
    phoneNo:"Phone Number",
    enterPhoneNo:"Renseignez votre numéro de téléphone",
    permissionDenied:"Accès refusé",
    emailCanNotBlank:"Désolé, la saisie de votre e-mail est obligatoire",
    enterValidEmail:"Prière d'entrer un e-mail valide",
    passwordCanNotBlank:"Désolé, la saisie de votre mot de passe est obligatoire",
    passwordMust6Long:"Votre mot de passe doit avoir au moins 6 caractères",
    pleaseEnterEmailID:"Prière de saisir votre e-mail",
    acceptPrivacyPolicy:"Prière d'accepter notre politique de confidentialité pour continuer",
    cityCantBlank:"Désolé, la saisie de votre ville est obligatoire",
    nameCantBlank:"Désolé, la saisie de votre nom est obligatoire",
    numberCantBlank:"Désolé, la saisie du numéro est obligatoire",
    enterValidPhoneNo:"Prière d'entrer un numéro de téléphone valide",
    typeHere:"Écrivez ici",
    notification:"Notification",
    category:"Catégorie",
    items:"Articles",
    filter:"Filtre",
    reset:"Réinitialiser",
    done:"Terminé",
    sortBy:"Trier par",
    costLTH:"Du moins cher au plus cher",
    costHTL:"Du plus cher au moins cher",
    mostPopular:"Le plus populaire",
    nearestMe:"Le plus proche de chez moi",
    shop:"Magasins",
    search:"Rechercher",
    price:"Prix",
    min:"Min",
    max:"Max",
    chat:"Chat",
    cart:"Panier",
    subTotal:"Sous-total",
    deliveryChanges:"Frais de livraison",
    tax:"Taxes",
    totalAmount:"Montant total",
    checkOut:"Passer à la caisse",
    profile:"Profil",
    address:"Adresse",
    orderHistory:"Historique de commande",
    currentOrder:"Commande en cours",
    wishList:"Produits favoris",
    payment:"Paiement",
    setting:"Réglages",
    shareApp:"Partagez l'application",
    logOut:"Se déconnecter",
    gps:"GPS",
    sms:"SMS",
    email:"Email",
    deleteAccount:"Supprimer votre compte NYOTA",
    clearHistory:"Supprimer votre historique de commande",
    paymentPurchaseTerm:"Faites votre paiement maintenant et bénéficier du programme de fidélité de votre opérateur Mobile Money",
    airtelMoney:"Airtel Money",
    mtnMobileMoney:"MTN Mobile Money (bientôt disponible)",
    paymentOnDelivery:"Payez à la livraison",
    cod:"Payer en cash à la livraison",
    outOfstock:"En rupture de stock",
    orderId:"Numéro de commande",
    purchaseDateTime:"Date et heure de la commande",
    estDelivery:"Délai de la livraison approximatif",
    orderAmount:"Montant de la commande",
    currentStatus:"Statut actuel",
    trackYourOrder:"Suivez votre commande",
    orderPlaced:"Commande passée",
    orderConfirm:"Commande prise en charge par NYOTA",
    packed:"Préparée",
    shiped:"Expédiée",
    delivered:"Livrée",
    price:"Prix",
    item:"Article",
    userCurrentLocation:"Me géo localiser (en considérant ma position actuelle)",
    addNewAddress:"Ajouter une nouvelle adresse",
    referencePoint:"Préciser un point de repère",
    enterReferencePoint:"Entrez un point de repère",
    street1:"Rue (numéro et nom)",
    enterStreet:"Saisissez votre rue (numéro et nom)",
    neighbourhood:"Quartier",
    selectNeighbourhood:"Sélectionner votre quartier",
    state:"Departement",
    enterState:"Indiquez votre département",
    phoneNo:"Numéro de téléphone",
    enterPhoneNo:"Indiquez votre numéro de téléphone",
    pincode:"Code PIN",
    enterPinCode:"Indiquez un code PIN",
    pleaseEnterAllFields:"Prière de renseigner tout les champs",
    pleaseSelectNeighBourhood:"Prière de sélectionner votre quartier",
    successfullyUpdate:"Mise à jour réussi!",
    changeLanguage:"Changer de langue",
    delete:"Supprimer",
    edit:"Modifier",
    successfullyAdded:"ajouté avec succès",
    cartEmpty:"Votre carte est actuellement vide",
    dateNTime:"Date et heure",
    noDataFound:"Aucune donnée disponible",
    cancelOrder:"annuler la commande",
    confirmYourPayment:"Confirmez votre paiement",
    orText:"ou",
    updateProfile:"Mettre à jour le profil",
    updateText:"Mise à jour",
    changePassword:"Changer le mot de passe",
    currentPassword:"Mot de passe actuel",
    newPassword:"Nouveau mot de passe",
    reEnterPassword:"Retaper le mot de passe",
    passwordDoesntMatch:"Le mot de passe ne correspond pas",
    afamapmh6c:"Tous les champs sont obligatoires et le mot de passe doit contenir au moins 6 caractères",
    paymentDoneSuccessfullyOrder:"Paiement effectué avec succès et votre commande",
    isConfirmed:"Est confirmé",
    thanksForOrder:"Merci d'avoir passé commande auprès de NYOTA",
    registerPassword:"Mot de passe",
    rating:"évaluation",
    okText:"D'accord",
    rateItText:"Évaluez-le !",
    selectAddressFirst:"Veuillez sélectionner l'adresse d'abord",
    makePaymentOf:"Effectuer le paiement de",
    noMoreItemAvailable:"Plus d'articles disponibles",
    reachWithmaxPrice:"Vous êtes atteint avec le prix maximum pour acheter le produit",
    selectSortOption:"Veuillez sélectionner l'option de tri",
    giveRatingToProduct:"Veuillez donner une note au produit",
    aboutThisProduct:"À propos de ce produit",
    commentText:"commentaires",
    viewAllText:"Voir tout",
    similarProductText:"produits similaires",
    rateTheProduct:"Évaluez le produit",
    goodText:"Bien",
    excellentText:"Excellent",
    horribleText:"horrible",
    badText:"Mauvais",
    moreReviewText:"Des avis plus détaillés pour plus de visibilité...",
    engText:"Anglais",
    frenchText:"Français",
    deliveryOption:'Options de livraison',
    standard:'la norme',
    express:'Express',
    updateOrder:'mise à jour\nde la commande',
    updateOrderHeader:'mise à jour de la commande',
    addingProductPopOption:"Ajout d'un produit dans l'ordre existant",
    addingExistingPopOption:"L'ajout de produit et la fusion avec votre panier actuel si la carte n'existe pas créera",
    addnewProduct:'Ajouter un nouveau produit',
    addMoreProduct:'Ajouter plus de produit',
    cancel:'Annuler',
    submit:'soumettre',
    popupNote:'* le panier sortant sera fusionné avec votre commande existante',
    modification:'Modification',
    shippingPrice:`prix de l'expédition`
}
});
export default strings;
