export const LOGIN = 'login';
export const REGISTER = 'register';
export const FORGOTPASSWORD = 'forgotpassword';
export const CHANGEPASSWORD = 'changepassword';
export const ABOUT_US = 'about-us';
export const PRIVACY_POLICY = 'privacy-policy';
export const VIEWPROFILE = 'details';
export const CATEGORY_DETAIL = 'categorydetail';
export const UPDATEPROFILE = 'updateprofile';
export const SIMILAR_PRODUCT = 'similarproduct';
export const CART_DATA = 'getcart';
export const GET_WISHLIST_DATA = 'getwishlist';
export const SETFILTER ='setfilter';
export const SUB_CATEGORY='subcategorylist';
//export const BASE_URL = 'http://nyota-app.com/api/'
// export const BASE_URL = 'http://nyota-app.com/nyotastaging/api/'
// export const BASE_URL = 'http://nyota-app.com/production/api/'

export const BASE_URL = 'http://nyota-app.com/nyotastaging/api/'